name: Deploy Hosting Dev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        working-directory: ./frontend
      - name: Install dependencies
        run: npm ci 
      - name: Build 
        run: CI='' npm run build
        env:
          REACT_APP_API_KEY: ${{ secrets.DEV_REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.DEV_REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.DEV_REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.DEV_REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.DEV_REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.DEV_REACT_APP_APP_ID }}
          REACT_APP_API_URL: ${{ secrets.DEV_REACT_APP_API_URL }}
          GENERATE_SOURCEMAP: false

      - name: Deploy live
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CACAOPHONY }}'
          channelId: live
          projectId: cacaophony

      - name: Deploy temporary url
        if: ${{ github.base_ref == 'master'  }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CACAOPHONY }}'
          expires: 1d
          projectId: cacaophony